# ==============================================================================
# File:             docker-compose.yml
# Purpose:          Docker Compose configuration for Memory Palace
# Author:           skr
# Owner:            MINT-RESEARCH / NeoMINT GmbH
# Contact:          mint-research@neomint.com
# License:          MIT / ? NeoMINT GmbH 2025
# Created:          2025-06-17
# Last Modified:    2025-06-17 by skr
# Status:           Stable
# Tags:             docker-compose, orchestration, memory-palace
# ==============================================================================

version: '3.8'

services:
  memory-palace:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: mint-mcp/memory-palace:latest
    container_name: mint-memory-palace
    environment:
      - MEMORY_PATH=/data/brain.fs
    volumes:
      - memory-data:/data
    restart: unless-stopped
    stdin_open: true
    tty: true
    labels:
      - "com.neomint.service=memory-palace"
      - "com.neomint.project=mint-mcp"

volumes:
  memory-data:
    name: mint-memory-palace-data